# -*- coding: utf-8 -*-
"""InternalAssessment1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lKSPJyuQe_WvioOwHCU8yV3FAWWQKpZT
"""

#Lab 1
#1
# enter length and width and meters and receive area and also categorize whether it is SMALL, MEDIUM or LARGE

length = int(input("Enter the length of the property (in m): "))
width = int(input("Enter the width of the property (in m): "))
area= length*width
print(area , "sq.m")

if area < 50:
  print("Small property")
elif area >= 50 and area <= 100:
  print("Medium Property")
else:
  print("Large Property")

#2
#height, weight, age.... bmi
height = int(input("Enter the height in cm : "))
weight = int(input("Enter the weight in kgs : "))


bmi = (weight/height)

if bmi < 16:
  print("Underweight and skinny, Need to eat more nutrients")
elif bmi >= 16 and bmi <21:
  print("Normal weight , maintain the diet")
elif bmi >= 21 and bmi <25:
  print("Overweight , do cardio and cut down excess")
else:
  print("Obese , hit the gym")

#3
#using dictionaries, add update retrieve student records
stu_details = {"name": "Ted",{"subject" : "eng","grade": "A"},{"subject":"Maths","grade":"B"}}

#Lab 2
#4
#age to recommend movies and tv shows, categorize to child-teen-adult-senior

age = int(input("Enter your age : "))
children = ["Wall E","Up","Toy Story"]
teen = ["Narnia","Harry Potter", "Avengers"]
Adult = ["Fight Club", "Taxi Driver", "Drive"]
Senior = ["Life of Pi",Adult,"The Intern"]

if age < 12:
  print("You have a Child and have access to U rated movies and here are some of reccomendations")
  for i in children:
    print(i)
elif age>=13 and age <18:
  print("You have a Teen and have access to U and also PG13 rated movies and here are some of reccomendations")
  for i in teen:
    print(i)
elif age>=18 and age <50:
  print("You have an Adult and have access to all kinds of movies and here are some of reccomendations")
  for i in Adult:
    print(i)
else:
  print("You have a senior and have access to all kinds of movies and here are some of reccomendations")
  for i in Senior:
    print(i)

#5
#create a list of even number subscriber ids
sub_list = ['1','2','3','4','5','6','7','8','9','10']
evensub = []
print(len(sub_list))
for i in range(len(sub_list)):
  if i%2 == 0:
    evensub.append(i)

print(evensub)

#6
#password , secure hashing
real_pass = "LVADSUSR191"
password = str(input("Enter the password : "))

if password == real_pass:
  print("Correct Password")
else:
  print("Try again")

#Lab 3
#7
#calculate avg scores and generate insights

scores = {10, 20 ,15, 30 ,45, 30}

sum=0
count =6
for i in scores:
  sum = sum+i

average_score = sum/count

print("The average scores of user rating is : " , average_score)

#8
# create func content moderation and counts vowels and filter out low effort content

def contentmod (comment):
  count =1
  for x in range(len(comment)):
    if x in {'a','e','i','o','u'}:
      count = count+1
  return count


comment = str(input("Enter the String value : "))
contentmod(comment)

#9
import datetime
upcoming_events = {}
schedules = {}

schedules.append(input("Enter the schedule"))

#Lab 4
#10
# loan repayment, savings interest and error handling

loan_amount = int(input("Enter the loan amount: "))
savings_amount= int(input("Enter the savings amount: "))

l_interest = 9
s_interest =3.5

loan = loan_amount* l_interest
savings = savings_amount* s_interest

print("Savings Amount : ",savings)
print("Loan Amount : ",loan)

try NetworkError:
  print("Network error is caused")
catch:
  print("Other error caused")

#11
#online polling app

print("Enter the data in the correct formats")

name, age, gender  =str(input("Enter your name : ")), int(input("Enter your age : ")) , str(input("Enter your gender : "))

print(name, age, gender)

#12
#scientific calculations and error handling
a = int(input("Enter the integer A :"))
b = int(input("Enter the integer B :"))

print("Addition of A and B is ", a+b)
print("Subraction of A and B is ", a-b)
print("Multiplication of A and B is ", a*b)
print("Division of A and B is ", a/b)
if ZeroDivisionError:
  print("Cannot be divided by Zero")

print("Remainder of A and B is ", a%b)

#Lab 5
#13
from os import read
import file
server_uptime = time.log
readfile = '\C:\Users\Documents\Python\IA1'
file.readfile()
time.log = append.server_uptime()

#14
# read from a log file

from os import read
import file

readfile(C:\Users\Documents\Python\IA1)

# Commented out IPython magic to ensure Python compatibility.
# #15
# #append daily data such as company news,stock performance and others and retrieve it daily
# 
# from os import read
# import fileinput
# 
# %%writefile [-a] tempfile
# 
#