# -*- coding: utf-8 -*-
"""IA2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s75IHo-3zS5Ll8FC4HBApH5CKwyloxFM
"""

#1
# print min, max, sum, mean and std

import numpy as np

data1 = [1,2,3,4,5,6,7]
arr=np.array(data1)
print("min value: ", arr.min())
print("max value: ", arr.max())
print("sum: ", arr.sum())
print("mean value: ", arr.mean())
print("std value: ", arr.std())

#2
import numpy as np

health_data = np.array([[160,70,30],
                       [165,65,35],
                       [170,75,40]])

#3

import numpy as np
import pandas as pd

stu_data = pd.read_csv('C:\Users\teja.varma.lv\Downloads\Q15_student_grades.csv')

#4
#sensor data

import numpy as np
a = [15,16,17,18,19,20,21,22,23,24,25]
sensor_data = np.array(a, ndmin=20)

print(sensor_data)

#5
#moving average over a window of 5 days

import numpy as np

daily_cp = np.array([100,102,98,105,107,110,108,112,115,118,120])
window_size = 5

print(daily_cp.std())

#6
import numpy as np
import pandas as pd

#7
# determinant of a matrix, matrix multiplication

import numpy as np
import pandas as pd

prop_m = ([ [1,2,3],
            [4,5,6],
            [7,8,9]])

#print(prop_m)
rev_m = np.array(prop_m).transpose()
#print(rev_m)
det_m = np.array(prop_m * rev_m)
print("The determinant matrix : is \n", det_m)

#8
import numpy as np
import pandas as pd

mat = ({'A':[[1,2,3],
        [4,5,6],
        [7,8,9]]})

df = pd.DataFrame(mat)
df[df['A'].values() > 5]

#9

import numpy as np
import pandas as pd

data = {'Name':['Alice','Bob','Charlie','David','Eve','Frank','Grace'],
        'Age' :[25,30,35,40,45,50,55],
        'City':['New York','Los Angeles','Chicago','Houston','Phoenix','Miami','Boston'],
        'Department':['HR','IT','Marketing','Finance','Sales','IT','HR']}

df = pd.DataFrame(data).filter('Age'.values() > 45)
print(df)

#10
import numpy as np
import pandas as pd

data = {
     'Department':['Electronics','Electronics','Clothing','Clothing','Home Goods'],
     'Sales Person' : ['Alice','Bob','Charlie','David','Eve'],
     'Sales' : [70000,50000,30000,40000,60000]
 }

df= pd.DataFrame(data)
df['Average Sales'] = df.groupby('Sales Person').agg('Sales'.values())
print(df)

#11
import numpy as np
import pandas as pd

data = {'Product':['Apples','Bananas','Cherry','Dates','Elderberries','Flour','Grapes'],
        'Category':['Fruit','Fruit','Fruit','Fruit','Fruit','Bakery','Fruit',],
        'Price': [1.20,0.50,3.00,2.50,4.00,1.50,2.00],
        'Promotion': ['True','False','True','True','False','True','False']
}

#12

import numpy as np
import pandas as pd

employee_data = {
    'Employee':['Alice','Bob','Charlie','David'],
    'Department':['HR','IT','Finance','IT'],
    'Manager':['John','Racheal','Emily','Racheal']
}

# dataset of employee project assignments
project_data = {
    'Employee':['Alice','Charlie','Eve'],
    'Project':['P1','P3','P2']
}

df1 = pd.DataFrame(employee_data)
df2 = pd.DataFrame(project_data)

df= df1 + df2
print(df)

#13
import numpy as np
import pandas as pd

#14
import numpy as np
import pandas as pd

#15
import numpy as np
import pandas as pd